# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGVjODIxYTAxNDc0OWU3Nzk4ZjU1OTQwNDIxZTlkZmM5OGNhOWY2MzkxZmU5MjA0MGY0MmJiYjU3OGMzY2QzNDY4YTc4NTQ4MmIyZjdjMGQ4YjFjNzUwMDBmZTEyY2Q0NjIzMDZmNmRlOTQ2NjJjOWYxM2ZhZDJkMWQ1MTQ1MjY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
